name: Duplicate Issue Check

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  check-duplicates:
    runs-on: ubuntu-latest
    env:
      SIMILARITY_THRESHOLD: 0.85
      THRESHOLD_LOOKS_LIKE: 0.5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run duplicate check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          n=0
          until [ $n -ge 2 ]
          do
            echo "Attempt $((n+1)) to run duplicate check..."
            node scripts/check-duplicates.js && break
            n=$((n+1))
            echo "Retrying duplicate check..."
            sleep 2
          done