name: Duplicate Issue Check

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  check-duplicates:
    runs-on: ubuntu-latest
    env:
      SIMILARITY_THRESHOLD: 0.85

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run duplicate check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: node scripts/check-duplicates.js